name: Documentation

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: dependencies
      env:
        dependency_packages: doxygen
      run: sudo apt-get update && sudo apt-get -y install ${dependency_packages}

    - name: build
      run: cd doc && doxygen ./Doxyfile

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./doc/html
